Support HOCON format
lvivco/mdcfg pull request #59
Opened 2024-07-29 09:24 UTC by alinadz720

2024-07-29 16:01 UTC, vstyran requested changes

2024-07-31 12:05 UTC, vstyran requested changes

2024-07-31 12:05 UTC, vstyran commented on src/main/java/org/mdcfg/source/HoconSource.java
> +            matcher.appendReplacement(res, rowNumber + matcher.group());
insert invisible ACII symbol between number and selector

2024-07-31 12:05 UTC, vstyran commented on src/main/java/org/mdcfg/source/HoconSource.java
> +    private final Pattern pattern = Pattern.compile("[a-zA-Z]*@");
format of selector could be     add-in*@[ls, panoramic-roof]: 55000

2024-08-01 09:22 UTC, vstyran commented on src/main/java/org/mdcfg/source/HoconSource.java
> +                .sorted(Comparator.comparing(e -> Integer.parseInt(e.getKey().substring(0, e.getKey().indexOf(MARKER)))))
may be split by marker then sort by splitt[0]  and then map[1] is better by performance

2024-08-01 09:22 UTC, vstyran commented on src/main/java/org/mdcfg/source/HoconSource.java
> +                .collect(Collectors.toMap(e -> e.getKey().substring(e.getKey().indexOf(MARKER) + 1),
and test with subkeys, probably will crash

2024-08-05 14:03 UTC, aolyvko approved these changes

2024-08-05 14:14 UTC, merged